name: MITRE ATT&CK Mapping Automation

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight
  push:
    branches:
      - main

jobs:
  mapping:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install attackcti requests

    - name: Run MITRE ATT&CK mapping script
      run: python map_cves.py

    - name: Commit and push results
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add cve_mitre_mapping.json
        git commit -m "Updated MITRE ATT&CK mappings"
        git push
